replicaCount: 1

image:
  repository: piomin/organization
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources: {}

env:
  - name: SPRING_CLOUD_BOOTSTRAP_ENABLED
    value: "true"
  - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLEAPI
    value: "true"
