apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "organization-service.fullname" . }}
  labels:
    app: {{ include "organization-service.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "organization-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "organization-service.name" . }}
    spec:
      serviceAccountName: spring-cloud-kubernetes
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: {{ .Values.service.port }}
        env:
          {{- range .Values.env }}
          - name: {{ .name }}
            value: {{ .value | quote }}
          {{- end }}
