apiVersion: v1
kind: Service
metadata:
  name: {{ include "organization-service.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "organization-service.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
