apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "admin-service.name" . }}
data:
  application.yml: |-
    spring:
      cloud:
        kubernetes:
          discovery:
            service-labels:
              spring-boot: true
