apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "admin-service.fullname" . }}
  labels:
    app: {{ include "admin-service.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "admin-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "admin-service.name" . }}
    spec:
      serviceAccountName: spring-cloud-kubernetes
      containers:
        - name: admin
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
          {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
